using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

var zitadelUrl = Environment.GetEnvironmentVariable("ZITADEL_URL") ?? "http://localhost:9080";
var patFilePath = Environment.GetEnvironmentVariable("ZITADEL_PAT_FILE")
    ?? Path.Combine(AppContext.BaseDirectory, ".zitadel", "pat-token");
var outputPath = Environment.GetEnvironmentVariable("CONFIG_OUTPUT_PATH") ?? "/app/config/zitadel-config.json";

Console.WriteLine("🚀 Starting Zitadel auto-configuration...");
Console.WriteLine($"Zitadel URL: {zitadelUrl}");

var httpClient = new HttpClient { BaseAddress = new Uri(zitadelUrl) };

// Wait for Zitadel to be ready
Console.WriteLine("⏳ Waiting for Zitadel to be healthy...");
var maxAttempts = 60;
var attempt = 0;
while (attempt < maxAttempts)
{
    try
    {
        var response = await httpClient.GetAsync("/debug/ready");
        if (response.IsSuccessStatusCode)
        {
            Console.WriteLine("✅ Zitadel is ready!");
            break;
        }
    }
    catch
    {
        // Ignore connection errors
    }

    attempt++;
    Console.WriteLine($"   Attempt {attempt}/{maxAttempts} - Zitadel not ready yet...");
    await Task.Delay(2000);
}

if (attempt == maxAttempts)
{
    Console.WriteLine("❌ Zitadel failed to become ready");
    Environment.Exit(1);
}

await Task.Delay(3000); // Give it a few more seconds

Console.WriteLine("🔑 Reading auto-generated PAT...");

// Step 1: Read PAT from file (auto-generated by Zitadel on first init) with retry
var patToken = await ReadPatWithRetryAsync(patFilePath);
httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {patToken}");
Console.WriteLine("✅ Authenticated with auto-generated PAT");

// Step 2: Check if project already exists
Console.WriteLine("🔍 Checking for existing SignalBeam project...");
var projectsResponse = await httpClient.PostAsync("/management/v1/projects/_search",
    JsonContent.Create(new { }));
var projectsData = await projectsResponse.Content.ReadFromJsonAsync<ProjectsSearchResponse>();

var existingProject = projectsData?.Result?.FirstOrDefault(p => p.Name == "SignalBeam Edge");
string projectId;

if (existingProject != null)
{
    projectId = existingProject.Id;
    Console.WriteLine($"✅ Found existing project: {projectId}");
}
else
{
    // Step 3: Create project
    Console.WriteLine("🏗️  Creating SignalBeam project...");
    var projectRequest = new { name = "SignalBeam Edge" };
    var projectResponse = await httpClient.PostAsync("/management/v1/projects",
        JsonContent.Create(projectRequest));

    if (!projectResponse.IsSuccessStatusCode)
    {
        var error = await projectResponse.Content.ReadAsStringAsync();
        Console.WriteLine($"❌ Failed to create project: {error}");
        Environment.Exit(1);
    }

    var projectData = await projectResponse.Content.ReadFromJsonAsync<ProjectResponse>();
    projectId = projectData!.Id;
    Console.WriteLine($"✅ Project created: {projectId}");
}

// Step 4: Check if application already exists
Console.WriteLine("🔍 Checking for existing application...");
var appsResponse = await httpClient.PostAsync($"/management/v1/projects/{projectId}/apps/_search",
    JsonContent.Create(new { }));
var appsData = await appsResponse.Content.ReadFromJsonAsync<AppsSearchResponse>();

var existingApp = appsData?.Result?.FirstOrDefault(a => a.Name == "SignalBeam Web");
string clientId;
string? apiClientId = null;
string? apiClientSecret = null;

if (existingApp != null)
{
    clientId = existingApp.ClientId ?? existingApp.Id;
    Console.WriteLine($"✅ Found existing application: {clientId}");
}
else
{
    // Step 5: Create OIDC application
    Console.WriteLine("📱 Creating web application...");
    var appRequest = new
    {
        name = "SignalBeam Web",
        redirectUris = new[] { "http://localhost:5173/callback", "http://localhost:5173/silent-renew" },
        postLogoutRedirectUris = new[] { "http://localhost:5173" },
        responseTypes = new[] { "OIDC_RESPONSE_TYPE_CODE" },
        grantTypes = new[] { "OIDC_GRANT_TYPE_AUTHORIZATION_CODE", "OIDC_GRANT_TYPE_REFRESH_TOKEN" },
        appType = "OIDC_APP_TYPE_USER_AGENT",
        authMethodType = "OIDC_AUTH_METHOD_TYPE_NONE",
        version = "OIDC_VERSION_1_0",
        devMode = true,
        accessTokenType = "OIDC_TOKEN_TYPE_JWT",
        idTokenRoleAssertion = true,
        idTokenUserinfoAssertion = true,
        clockSkew = "0s"
    };

    var appResponse = await httpClient.PostAsync($"/management/v1/projects/{projectId}/apps/oidc",
        JsonContent.Create(appRequest));

    if (!appResponse.IsSuccessStatusCode)
    {
        var error = await appResponse.Content.ReadAsStringAsync();
        Console.WriteLine($"❌ Failed to create application: {error}");
        Environment.Exit(1);
    }

    var appData = await appResponse.Content.ReadFromJsonAsync<AppResponse>();
    clientId = appData!.ClientId;
    Console.WriteLine($"✅ Application created: {clientId}");
}

// Step 5: Check if API application already exists
Console.WriteLine("🔍 Checking for existing API application...");
var existingApiApp = appsData?.Result?.FirstOrDefault(a => a.Name == "SignalBeam API");

if (existingApiApp != null)
{
    apiClientId = existingApiApp.ClientId ?? existingApiApp.Id;
    Console.WriteLine($"✅ Found existing API application: {apiClientId}");
}
else
{
    // Step 6: Create API application
    Console.WriteLine("🧩 Creating API application...");
    var apiRequest = new
    {
        name = "SignalBeam API",
        authMethodType = "API_AUTH_METHOD_TYPE_BASIC"
    };

    var apiResponse = await httpClient.PostAsync($"/management/v1/projects/{projectId}/apps/api",
        JsonContent.Create(apiRequest));

    if (!apiResponse.IsSuccessStatusCode)
    {
        var error = await apiResponse.Content.ReadAsStringAsync();
        Console.WriteLine($"❌ Failed to create API application: {error}");
        Environment.Exit(1);
    }

    var apiData = await apiResponse.Content.ReadFromJsonAsync<AppResponse>();
    apiClientId = apiData!.ClientId;
    apiClientSecret = apiData.ClientSecret;
    Console.WriteLine($"✅ API application created: {apiClientId}");
}

// Step 6: Save configuration
Console.WriteLine($"💾 Saving configuration to {outputPath}...");

var config = new
{
    zitadel = new
    {
        authority = "http://localhost:8080",
        clientId = clientId,
        projectId = projectId,
        redirectUri = "http://localhost:5173/callback",
        postLogoutRedirectUri = "http://localhost:5173",
        scope = "openid profile email"
    },
    backend = new
    {
        authority = "http://localhost:8080",
        audience = projectId,
        requireHttpsMetadata = false
    }
};

var directory = Path.GetDirectoryName(outputPath);
if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
{
    Directory.CreateDirectory(directory);
}

var jsonOptions = new JsonSerializerOptions { WriteIndented = true };
await File.WriteAllTextAsync(outputPath, JsonSerializer.Serialize(config, jsonOptions));

WriteWebEnvFile(clientId, projectId);
WriteApiEnvFile(clientId, apiClientId, apiClientSecret);

Console.WriteLine("✅ Configuration saved!");
Console.WriteLine();
Console.WriteLine("📋 Zitadel Configuration:");
Console.WriteLine($"  Project ID:  {projectId}");
Console.WriteLine($"  Client ID:   {clientId}");
Console.WriteLine($"  API Client:  {apiClientId ?? "<existing>"}");
Console.WriteLine($"  Authority:   http://localhost:8080");
Console.WriteLine();
Console.WriteLine("🎉 Zitadel is fully configured and ready to use!");

static void WriteWebEnvFile(string clientId, string projectId)
{
    var repoRoot = FindRepoRoot();
    if (repoRoot is null)
    {
        Console.WriteLine("⚠️  Could not find repo root to write web/.env.development");
        return;
    }

    var envPath = Path.Combine(repoRoot, "web", ".env.development");
    if (!File.Exists(envPath))
    {
        Console.WriteLine($"⚠️  web/.env.development not found at {envPath}");
        return;
    }

    var replacements = new Dictionary<string, string>
    {
        ["VITE_ZITADEL_CLIENT_ID"] = clientId,
        ["VITE_ZITADEL_PROJECT_ID"] = projectId,
    };

    var existing = File.ReadAllLines(envPath);
    var updated = new List<string>();
    var found = new HashSet<string>();

    foreach (var line in existing)
    {
        var replaced = false;
        foreach (var (key, value) in replacements)
        {
            if (line.StartsWith($"{key}=", StringComparison.Ordinal))
            {
                updated.Add($"{key}={value}");
                found.Add(key);
                replaced = true;
                break;
            }
        }

        if (!replaced)
        {
            updated.Add(line);
        }
    }

    foreach (var (key, value) in replacements)
    {
        if (!found.Contains(key))
        {
            updated.Add($"{key}={value}");
        }
    }

    File.WriteAllLines(envPath, updated);
    Console.WriteLine($"✅ Updated VITE_ZITADEL_CLIENT_ID and VITE_ZITADEL_PROJECT_ID in {envPath}");
}

static void WriteApiEnvFile(string webClientId, string? apiClientId, string? apiClientSecret)
{
    if (string.IsNullOrWhiteSpace(apiClientId) || string.IsNullOrWhiteSpace(apiClientSecret))
    {
        Console.WriteLine("⚠️  API client secret not available; skipping .env.zitadel.local write");
        return;
    }

    var directory = AppContext.BaseDirectory;
    while (directory is not null)
    {
        var gitDir = Path.Combine(directory, ".git");
        var slnPath = Path.Combine(directory, "src", "SignalBeam.sln");
        if (Directory.Exists(gitDir) || File.Exists(slnPath))
        {
            var envPath = Path.Combine(directory, ".env.zitadel.local");
            var content = $"""
                # Auto-generated by SignalBeam.ZitadelSetup - do not commit
                ZITADEL_WEB_CLIENT_ID={webClientId}
                ZITADEL_API_CLIENT_ID={apiClientId}
                ZITADEL_API_CLIENT_SECRET={apiClientSecret}
                """;
            File.WriteAllText(envPath, content);
            Console.WriteLine($"✅ Wrote API client credentials to {envPath}");
            return;
        }

        directory = Directory.GetParent(directory)?.FullName;
    }

    Console.WriteLine("⚠️  Could not find repo root to write .env.zitadel.local");
}

static string? FindRepoRoot()
{
    // Prefer explicit REPO_ROOT from Aspire AppHost
    var repoRoot = Environment.GetEnvironmentVariable("REPO_ROOT");
    if (!string.IsNullOrWhiteSpace(repoRoot) && Directory.Exists(repoRoot))
    {
        return repoRoot;
    }

    var candidates = new[]
    {
        Directory.GetCurrentDirectory(),
        AppContext.BaseDirectory
    };

    foreach (var start in candidates)
    {
        var directory = start;
        while (!string.IsNullOrEmpty(directory))
        {
            var gitDir = Path.Combine(directory, ".git");
            var slnPath = Path.Combine(directory, "src", "SignalBeam.sln");
            if (Directory.Exists(gitDir) || File.Exists(slnPath))
            {
                return directory;
            }

            directory = Directory.GetParent(directory)?.FullName ?? string.Empty;
        }
    }

    return null;
}

static async Task<string> ReadPatWithRetryAsync(string patFilePath)
{
    var delays = new[] { 2000, 3000, 5000, 8000, 10000 }; // Backoff: 2s, 3s, 5s, 8s, 10s

    for (var attempt = 0; attempt < delays.Length; attempt++)
    {
        if (File.Exists(patFilePath))
        {
            var token = (await File.ReadAllTextAsync(patFilePath)).Trim();
            if (!string.IsNullOrWhiteSpace(token))
            {
                Console.WriteLine($"   ✅ PAT file found at {patFilePath}");
                return token;
            }
        }

        Console.WriteLine($"   Waiting for PAT file ({attempt + 1}/{delays.Length})... {patFilePath}");
        await Task.Delay(delays[attempt]);
    }

    Console.WriteLine("❌ PAT file was not created by Zitadel");
    Console.WriteLine($"   Expected path: {patFilePath}");
    Console.WriteLine("\n💡 Ensure Zitadel is configured with:");
    Console.WriteLine("   ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME");
    Console.WriteLine("   ZITADEL_FIRSTINSTANCE_PATPATH");
    Environment.Exit(1);
    return string.Empty; // Unreachable
}

// Record types for JSON deserialization
record ProjectResponse(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name
);

record ProjectsSearchResponse(
    [property: JsonPropertyName("result")] List<ProjectResponse> Result
);

record AppResponse(
    [property: JsonPropertyName("appId")] string AppId,
    [property: JsonPropertyName("clientId")] string ClientId,
    [property: JsonPropertyName("clientSecret")] string? ClientSecret
);

record AppSearchResult(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("oidcConfig")] OidcConfig? OidcConfig,
    [property: JsonPropertyName("apiConfig")] ApiConfig? ApiConfig
)
{
    public string? ClientId => OidcConfig?.ClientId ?? ApiConfig?.ClientId;
}

record OidcConfig(
    [property: JsonPropertyName("clientId")] string? ClientId
);

record ApiConfig(
    [property: JsonPropertyName("clientId")] string? ClientId
);

record AppsSearchResponse(
    [property: JsonPropertyName("result")] List<AppSearchResult> Result
);
