replicaCount: 1

image:
  tag: "latest"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

config:
  ASPNETCORE_ENVIRONMENT: Development
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.signalbeam:4317"

serviceMonitor:
  enabled: false
