<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EdgeAgent\SignalBeam.EdgeAgent.Application\SignalBeam.EdgeAgent.Application.csproj" />
    <ProjectReference Include="..\..\src\EdgeAgent\SignalBeam.EdgeAgent.Infrastructure\SignalBeam.EdgeAgent.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\EdgeAgent\SignalBeam.EdgeAgent.Host\SignalBeam.EdgeAgent.Host.csproj" />
    <ProjectReference Include="..\..\src\Shared\SignalBeam.Domain\SignalBeam.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
    <Using Include="NSubstitute" />
  </ItemGroup>

</Project>
