#!/bin/bash
set -e

# Update Frontend .env.development with Zitadel configuration
# This script reads the generated Zitadel config and updates the frontend environment file

CONFIG_FILE="${1:-/tmp/signalbeam-zitadel-config.json}"
ENV_FILE="$(dirname "$0")/../web/.env.development"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Config file not found: $CONFIG_FILE"
    echo "💡 Run the Zitadel setup tool first: cd src/SignalBeam.ZitadelSetup && dotnet run"
    exit 1
fi

echo "📝 Reading Zitadel configuration from: $CONFIG_FILE"

# Extract values using jq
CLIENT_ID=$(jq -r '.zitadel.clientId' "$CONFIG_FILE")
AUTHORITY=$(jq -r '.zitadel.authority' "$CONFIG_FILE")

if [ "$CLIENT_ID" == "null" ] || [ -z "$CLIENT_ID" ]; then
    echo "❌ Failed to read Client ID from config file"
    exit 1
fi

echo "✅ Client ID: $CLIENT_ID"
echo "✅ Authority: $AUTHORITY"

# Update .env.development
echo "📝 Updating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Zitadel OIDC Configuration
# Auto-generated by scripts/update-frontend-config.sh
# Source: $CONFIG_FILE

VITE_ZITADEL_AUTHORITY=$AUTHORITY
VITE_ZITADEL_CLIENT_ID=$CLIENT_ID
VITE_ZITADEL_REDIRECT_URI=http://localhost:5173/callback
VITE_ZITADEL_POST_LOGOUT_REDIRECT_URI=http://localhost:5173
VITE_ZITADEL_SCOPE=openid profile email

# API Gateway
VITE_API_BASE_URL=http://localhost:8080

# Authentication Mode (zitadel, entra-id, api-key)
VITE_AUTH_MODE=zitadel
EOF

echo "✅ Frontend configuration updated!"
echo ""
echo "🚀 You can now start the frontend:"
echo "   cd web"
echo "   npm run dev"
