// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SignalBeam.BundleOrchestrator.Infrastructure.Persistence;

#nullable disable

namespace SignalBeam.BundleOrchestrator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BundleDbContext))]
    [Migration("20251225213451_AddRolloutManagementTables")]
    partial class AddRolloutManagementTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bundle_orchestrator")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SignalBeam.Domain.Entities.AppBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("latest_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_app_bundles_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_app_bundles_tenant_id_name");

                    b.ToTable("app_bundles", "bundle_orchestrator");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.AppBundleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobStorageUri")
                        .HasColumnType("text")
                        .HasColumnName("blob_storage_uri");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_id");

                    b.Property<string>("Checksum")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("checksum");

                    b.Property<string>("Containers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("containers");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("text")
                        .HasColumnName("release_notes");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("BundleId")
                        .HasDatabaseName("ix_app_bundle_versions_bundle_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_app_bundle_versions_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_app_bundle_versions_status");

                    b.HasIndex("BundleId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_app_bundle_versions_bundle_id_version");

                    b.ToTable("app_bundle_versions", "bundle_orchestrator");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.DeviceDesiredState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_id");

                    b.Property<string>("BundleVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bundle_version");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("ix_device_desired_states_assigned_at");

                    b.HasIndex("BundleId")
                        .HasDatabaseName("ix_device_desired_states_bundle_id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_desired_states_device_id");

                    b.ToTable("device_desired_states", "bundle_orchestrator");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.Rollout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentPhaseNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_phase_number");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("FailureThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.05m)
                        .HasColumnName("failure_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PreviousVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("previous_version");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetDeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_device_group_id");

                    b.Property<string>("TargetVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("BundleId")
                        .HasDatabaseName("ix_rollouts_bundle_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_rollouts_created_at");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_rollouts_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rollouts_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_rollouts_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_rollouts_tenant_id_status");

                    b.ToTable("rollouts", "bundle_orchestrator");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.RolloutDeviceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phase_id");

                    b.Property<DateTimeOffset?>("ReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconciled_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uuid")
                        .HasColumnName("rollout_id");

                    b.Property<Guid?>("RolloutPhaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_rollout_device_assignments_device_id");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("ix_rollout_device_assignments_phase_id");

                    b.HasIndex("RolloutId")
                        .HasDatabaseName("ix_rollout_device_assignments_rollout_id");

                    b.HasIndex("RolloutPhaseId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rollout_device_assignments_status");

                    b.HasIndex("PhaseId", "Status")
                        .HasDatabaseName("ix_rollout_device_assignments_phase_id_status");

                    b.HasIndex("RolloutId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_rollout_device_assignments_rollout_id_device_id");

                    b.ToTable("rollout_device_assignments", "bundle_orchestrator");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.RolloutPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failure_count");

                    b.Property<long?>("MinHealthyDuration")
                        .HasColumnType("bigint")
                        .HasColumnName("min_healthy_duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("PhaseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("phase_number");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uuid")
                        .HasColumnName("rollout_id");

                    b.Property<Guid?>("RolloutId1")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("success_count");

                    b.Property<int>("TargetDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_device_count");

                    b.Property<decimal?>("TargetPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("target_percentage");

                    b.HasKey("Id");

                    b.HasIndex("RolloutId")
                        .HasDatabaseName("ix_rollout_phases_rollout_id");

                    b.HasIndex("RolloutId1");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rollout_phases_status");

                    b.HasIndex("RolloutId", "PhaseNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_rollout_phases_rollout_id_phase_number");

                    b.ToTable("rollout_phases", "bundle_orchestrator");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.RolloutStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_id");

                    b.Property<string>("BundleVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bundle_version");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uuid")
                        .HasColumnName("rollout_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_rollout_statuses_completed_at");

                    b.HasIndex("RolloutId")
                        .HasDatabaseName("ix_rollout_statuses_rollout_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_rollout_statuses_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rollout_statuses_status");

                    b.HasIndex("RolloutId", "Status")
                        .HasDatabaseName("ix_rollout_statuses_rollout_id_status");

                    b.HasIndex("DeviceId", "BundleId", "BundleVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_rollout_statuses_device_bundle_version");

                    b.ToTable("rollout_statuses", "bundle_orchestrator");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.RolloutDeviceAssignment", b =>
                {
                    b.HasOne("SignalBeam.Domain.Entities.RolloutPhase", null)
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBeam.Domain.Entities.RolloutPhase", null)
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("RolloutPhaseId");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.RolloutPhase", b =>
                {
                    b.HasOne("SignalBeam.Domain.Entities.Rollout", null)
                        .WithMany()
                        .HasForeignKey("RolloutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBeam.Domain.Entities.Rollout", null)
                        .WithMany("Phases")
                        .HasForeignKey("RolloutId1");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.Rollout", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("SignalBeam.Domain.Entities.RolloutPhase", b =>
                {
                    b.Navigation("DeviceAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
