namespace SignalBeam.TelemetryProcessor.Application.Services.AlertRules;

/// <summary>
/// Configuration options for the alerting system.
/// </summary>
public class AlertingOptions
{
    public const string SectionName = "Alerting";

    /// <summary>
    /// Alert rule configurations.
    /// </summary>
    public AlertRulesOptions Rules { get; set; } = new();
}

/// <summary>
/// Configuration for all alert rules.
/// </summary>
public class AlertRulesOptions
{
    /// <summary>
    /// Device offline warning rule configuration.
    /// </summary>
    public AlertRuleConfig DeviceOfflineWarning { get; set; } = new()
    {
        Enabled = true,
        ThresholdMinutes = 5,
        Severity = "Warning"
    };

    /// <summary>
    /// Device offline critical rule configuration.
    /// </summary>
    public AlertRuleConfig DeviceOfflineCritical { get; set; } = new()
    {
        Enabled = true,
        ThresholdMinutes = 30,
        Severity = "Critical"
    };

    /// <summary>
    /// Device unhealthy rule configuration.
    /// </summary>
    public AlertRuleConfig DeviceUnhealthy { get; set; } = new()
    {
        Enabled = true,
        ThresholdScore = 50,
        Severity = "Critical"
    };

    /// <summary>
    /// High error rate rule configuration.
    /// </summary>
    public AlertRuleConfig HighErrorRate { get; set; } = new()
    {
        Enabled = true,
        ThresholdPercent = 5,
        WindowMinutes = 5,
        Severity = "Warning"
    };
}

/// <summary>
/// Configuration for a single alert rule.
/// </summary>
public class AlertRuleConfig
{
    /// <summary>
    /// Whether the rule is enabled.
    /// </summary>
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Threshold in minutes for time-based rules.
    /// </summary>
    public int ThresholdMinutes { get; set; }

    /// <summary>
    /// Threshold percentage for rate-based rules.
    /// </summary>
    public double ThresholdPercent { get; set; }

    /// <summary>
    /// Threshold score for health-based rules.
    /// </summary>
    public int ThresholdScore { get; set; }

    /// <summary>
    /// Time window in minutes for aggregation.
    /// </summary>
    public int WindowMinutes { get; set; }

    /// <summary>
    /// Severity level for alerts generated by this rule (Info, Warning, Critical).
    /// </summary>
    public string Severity { get; set; } = "Warning";
}
