# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "dev/aca/secrets/terraform.tfstate"
    resource_group_name  = "sb-tfstate-dev-weu"
    storage_account_name = "sbtfstatedevweu"
    subscription_id      = "YOUR_SUBSCRIPTION_ID_HERE"
  }
}
