name: Build Web

on:
  push:
    branches: [main]
    paths:
      - 'web/**'
    tags: ['v*']
  pull_request:
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: web
      dockerfile: ./web/Dockerfile
      context: ./web
